// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_win_100_all_fives_dominoes = "CgkI6u-LybYREAIQDA"; // <GPGSID>
        public const string achievement_bonus_10000 = "CgkI6u-LybYREAIQCA"; // <GPGSID>
        public const string achievement_bonus_100 = "CgkI6u-LybYREAIQBA"; // <GPGSID>
        public const string event_block_dominoes_win = "CgkI6u-LybYREAIQEw"; // <GPGSID>
        public const string achievement_bonus_10 = "CgkI6u-LybYREAIQAw"; // <GPGSID>
        public const string achievement_bonus_5000 = "CgkI6u-LybYREAIQBw"; // <GPGSID>
        public const string event_win = "CgkI6u-LybYREAIQAA"; // <GPGSID>
        public const string achievement_win_500_all_fives_dominoes = "CgkI6u-LybYREAIQDw"; // <GPGSID>
        public const string achievement_bonus_50000 = "CgkI6u-LybYREAIQCQ"; // <GPGSID>
        public const string achievement_win_100_block_dominoes = "CgkI6u-LybYREAIQCw"; // <GPGSID>
        public const string achievement_bonus_500 = "CgkI6u-LybYREAIQBQ"; // <GPGSID>
        public const string leaderboard_score_leaderboards = "CgkI6u-LybYREAIQAg"; // <GPGSID>
        public const string achievement_win_500_block_dominoes = "CgkI6u-LybYREAIQDg"; // <GPGSID>
        public const string event_lose = "CgkI6u-LybYREAIQAQ"; // <GPGSID>
        public const string achievement_win_500_draw_dominoes = "CgkI6u-LybYREAIQDQ"; // <GPGSID>
        public const string achievement_bonus_1000 = "CgkI6u-LybYREAIQBg"; // <GPGSID>
        public const string event_game_played = "CgkI6u-LybYREAIQEQ"; // <GPGSID>
        public const string achievement_win_100_draw_dominoes = "CgkI6u-LybYREAIQCg"; // <GPGSID>
        public const string event_all_fives_dominoes_win = "CgkI6u-LybYREAIQFA"; // <GPGSID>
        public const string event_draw_dominoes_win = "CgkI6u-LybYREAIQEg"; // <GPGSID>

}

